version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARIZE_SPACE_ID=${ARIZE_SPACE_ID}
      - ARIZE_API_KEY=${ARIZE_API_KEY}
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - protein-tracker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    networks:
      - protein-tracker

networks:
  protein-tracker:
    driver: bridge